services:

  postgres:
    image: postgres:16
    container_name: ig-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  collector:
    build: ./collector
    container_name: ig-collector
    depends_on:
      - postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  grafana:
    user: "472"
    image: grafana/grafana
    container_name: ig-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - postgres
