apiVersion: 1

prune: true

datasources:
  - name: InfraGuardian-Postgres
    type: postgres
    access: proxy
    url: $POSTGRES_HOST:$POSTGRES_PORT
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
    version: 2
